export const DEFAULT_RESOURCE_CATEGORIES = [
  { name: "Assessment Tools", slug: "assessment-tools" },
  { name: "Report Templates", slug: "report-templates" },
  { name: "Psychoeducation", slug: "psychoeducation" },
  { name: "Parent Handouts", slug: "parent-handouts" },
  { name: "NDIS Resources", slug: "ndis-resources" },
  { name: "Therapy Worksheets", slug: "therapy-worksheets" },
  { name: "ADHD Supports", slug: "adhd-supports" },
  {
    name: "Autism and Neurodivergent Practice",
    slug: "autism-and-neurodivergent-practice",
  },
  { name: "Sensory Supports", slug: "sensory-supports" },
  { name: "Social Skills", slug: "social-skills" },
  { name: "Executive Function", slug: "executive-function" },
  { name: "Emotional Regulation", slug: "emotional-regulation-tools" },
  { name: "Behaviour Supports", slug: "behaviour-supports" },
  { name: "Behavioural Activation", slug: "behavioural-activation" },
  { name: "Burnout and Wellbeing", slug: "burnout-and-wellbeing" },
  { name: "Trauma-Informed Practice", slug: "trauma-informed-practice" },
  { name: "Adult Therapy Tools", slug: "adult-therapy-tools" },
  { name: "Coping Skills Packs", slug: "coping-skills-packs" },
  { name: "Communication Supports", slug: "communication-supports" },
  { name: "Couples and Relationships", slug: "couples-and-relationships" },
  { name: "Clinical Documentation", slug: "clinical-documentation" },
  { name: "Feedback and Formulation", slug: "feedback-and-formulation" },
  { name: "Motivation and Routines", slug: "motivation-and-routines" },
  {
    name: "Supervision and Practice Management",
    slug: "supervision-and-practice-management",
  },
  { name: "School and Classroom Supports", slug: "school-and-classroom-supports" },
  { name: "Autism Assessments", slug: "autism-assessments" },
] satisfies { name: string; slug: string }[];

export const DEFAULT_RESOURCE_TAGS = [
  { name: "ADHD", slug: "adhd" },
  { name: "Autism", slug: "autism" },
  { name: "Alexithymia", slug: "alexithymia" },
  { name: "Trauma", slug: "trauma" },
  { name: "Anxiety", slug: "anxiety" },
  { name: "NDIS", slug: "ndis" },
  { name: "Child", slug: "child" },
  { name: "Adolescent", slug: "adolescent" },
  { name: "Parent", slug: "parent" },
  { name: "CBT", slug: "cbt" },
  { name: "DBT", slug: "dbt" },
  { name: "Emotional Regulation", slug: "emotional-regulation" },
  { name: "Adults", slug: "adults" },
  { name: "Burnout", slug: "burnout" },
  { name: "Sensory", slug: "sensory" },
  { name: "Executive Functioning", slug: "executive-functioning" },
  { name: "Depression", slug: "depression" },
  { name: "OCD", slug: "ocd" },
  { name: "Grief", slug: "grief" },
  { name: "Sleep", slug: "sleep" },
  { name: "Mindfulness", slug: "mindfulness" },
  { name: "Self-Compassion", slug: "self-compassion" },
  { name: "Attachment", slug: "attachment" },
  { name: "Relationships", slug: "relationships" },
  { name: "School Refusal", slug: "school-refusal" },
  { name: "Behaviour Support", slug: "behaviour-support" },
  { name: "Goal Setting", slug: "goal-setting" },
  { name: "Case Formulation", slug: "case-formulation" },
  { name: "Social Skills", slug: "social-skills" },
  { name: "Communication", slug: "communication" },
  { name: "Interoception", slug: "interoception" },
  { name: "Therapist Tools", slug: "therapist-tools" },
  { name: "Assessment", slug: "assessment" },
  { name: "Feedback Sessions", slug: "feedback-sessions" },
  { name: "Report Writing", slug: "report-writing" },
  { name: "Functional Impact", slug: "functional-impact" },
  { name: "Clinical Documentation", slug: "clinical-documentation" },
  { name: "Handouts", slug: "handouts" },
  { name: "Behavioural Activation", slug: "behavioural-activation" },
  { name: "Motivation", slug: "motivation" },
  { name: "Routine Building", slug: "routine-building" },
  { name: "Neurodiversity-Affirming", slug: "neurodiversity-affirming" },
  { name: "Demand Avoidance", slug: "demand-avoidance" },
  { name: "Daily Living", slug: "daily-living" },
  { name: "Support Letters", slug: "support-letters" },
  { name: "Printable", slug: "printable" },
  { name: "Session Planning", slug: "session-planning" },
  { name: "Parent Coaching", slug: "parent-coaching" },
  { name: "PDA", slug: "pda" },
  { name: "AuDHD", slug: "audhd" },
] satisfies { name: string; slug: string }[];

export const HOMEPAGE_FEATURED_CATEGORY_SLUGS = [
  "psychoeducation",
  "report-templates",
  "ndis-resources",
  "therapy-worksheets",
  "parent-handouts",
  "emotional-regulation-tools",
  "trauma-informed-practice",
  "assessment-tools",
] as const;
