export const DEFAULT_RESOURCE_CATEGORIES = [
  { name: "Assessment Tools", slug: "assessment-tools" },
  { name: "Report Templates", slug: "report-templates" },
  { name: "Templates and Frameworks", slug: "templates-and-frameworks" },
  { name: "Clinical Documentation", slug: "clinical-documentation" },
  { name: "Progress Notes and Session Records", slug: "progress-notes-and-session-records" },
  { name: "Feedback and Formulation", slug: "feedback-and-formulation" },
  { name: "Goal Setting and Intervention Plans", slug: "goal-setting-and-intervention-plans" },
  { name: "Psychoeducation", slug: "psychoeducation" },
  { name: "Therapy Worksheets", slug: "therapy-worksheets" },
  { name: "Parent Handouts", slug: "parent-handouts" },
  { name: "Home Programs and Carryover", slug: "home-programs-and-carryover" },
  { name: "School and Classroom Supports", slug: "school-and-classroom-supports" },
  { name: "NDIS Resources", slug: "ndis-resources" },
  { name: "Medicare Resources", slug: "medicare-resources" },
  { name: "Functional Capacity Assessments", slug: "functional-capacity-assessments" },
  { name: "Positive Behaviour Support", slug: "positive-behaviour-support" },
  { name: "Behaviour Support Plans", slug: "behaviour-support-plans" },
  { name: "Behaviour Supports", slug: "behaviour-supports" },
  { name: "Emotional Regulation", slug: "emotional-regulation-tools" },
  { name: "Executive Function", slug: "executive-function" },
  { name: "Social Skills", slug: "social-skills" },
  { name: "Communication Supports", slug: "communication-supports" },
  { name: "Sensory Supports", slug: "sensory-supports" },
  { name: "ADHD Supports", slug: "adhd-supports" },
  {
    name: "Autism and Neurodivergent Practice",
    slug: "autism-and-neurodivergent-practice",
  },
  { name: "Autism Assessments", slug: "autism-assessments" },
  { name: "Trauma-Informed Practice", slug: "trauma-informed-practice" },
  { name: "Burnout and Wellbeing", slug: "burnout-and-wellbeing" },
  { name: "Behavioural Activation", slug: "behavioural-activation" },
  { name: "Adult Therapy Tools", slug: "adult-therapy-tools" },
  { name: "Couples and Relationships", slug: "couples-and-relationships" },
  { name: "Motivation and Routines", slug: "motivation-and-routines" },
  { name: "Psychology Resources", slug: "psychology-resources" },
  { name: "Provisional Psychology Resources", slug: "provisional-psychology-resources" },
  { name: "Clinical Psychology Resources", slug: "clinical-psychology-resources" },
  { name: "Developmental Psychology Resources", slug: "developmental-psychology-resources" },
  {
    name: "Educational and Developmental Psychology",
    slug: "educational-and-developmental-psychology",
  },
  { name: "Organisational Psychology Resources", slug: "organisational-psychology-resources" },
  { name: "Occupational Therapy Resources", slug: "occupational-therapy-resources" },
  { name: "Speech Pathology Resources", slug: "speech-pathology-resources" },
  { name: "Physiotherapy Resources", slug: "physiotherapy-resources" },
  { name: "Admin Templates and Forms", slug: "admin-templates-and-forms" },
  { name: "Informed Consent and Intake", slug: "informed-consent-and-intake" },
  { name: "Service Agreements and Policies", slug: "service-agreements-and-policies" },
  { name: "Invoices and Finance", slug: "invoices-and-finance" },
  { name: "Letters and Referrals", slug: "letters-and-referrals" },
  { name: "Telehealth Resources", slug: "telehealth-resources" },
  { name: "Group Programs", slug: "group-programs" },
  {
    name: "Supervision and Practice Management",
    slug: "supervision-and-practice-management",
  },
  { name: "Private Practice Systems", slug: "private-practice-systems" },
] satisfies { name: string; slug: string }[];

export const DEFAULT_RESOURCE_TAGS = [
  { name: "Psychologist", slug: "psychologist" },
  { name: "Provisional Psychologist", slug: "provisional-psychologist" },
  { name: "Clinical Psychologist", slug: "clinical-psychologist" },
  { name: "Developmental Psychologist", slug: "developmental-psychologist" },
  {
    name: "Educational and Developmental Psychologist",
    slug: "educational-and-developmental-psychologist",
  },
  { name: "Organisational Psychologist", slug: "organisational-psychologist" },
  { name: "Psychology", slug: "psychology" },
  { name: "Occupational Therapist", slug: "occupational-therapist" },
  { name: "Occupational Therapy", slug: "occupational-therapy" },
  { name: "Speech Pathologist", slug: "speech-pathologist" },
  { name: "Speech Pathology", slug: "speech-pathology" },
  { name: "Physiotherapist", slug: "physiotherapist" },
  { name: "Physiotherapy", slug: "physiotherapy" },
  {
    name: "Positive Behaviour Support Practitioner",
    slug: "positive-behaviour-support-practitioner",
  },
  { name: "Positive Behaviour Support", slug: "positive-behaviour-support" },
  { name: "Behaviour Support Practitioner", slug: "behaviour-support-practitioner" },
  { name: "Allied Health", slug: "allied-health" },
  { name: "Practice Manager", slug: "practice-manager" },
  { name: "ADHD", slug: "adhd" },
  { name: "Autism", slug: "autism" },
  { name: "AuDHD", slug: "audhd" },
  { name: "Alexithymia", slug: "alexithymia" },
  { name: "Trauma", slug: "trauma" },
  { name: "Anxiety", slug: "anxiety" },
  { name: "Depression", slug: "depression" },
  { name: "OCD", slug: "ocd" },
  { name: "Grief", slug: "grief" },
  { name: "Sleep", slug: "sleep" },
  { name: "Burnout", slug: "burnout" },
  { name: "Attachment", slug: "attachment" },
  { name: "PDA", slug: "pda" },
  { name: "Sensory", slug: "sensory" },
  { name: "Sensory Processing", slug: "sensory-processing" },
  { name: "Interoception", slug: "interoception" },
  { name: "Executive Functioning", slug: "executive-functioning" },
  { name: "Emotional Regulation", slug: "emotional-regulation" },
  { name: "Social Skills", slug: "social-skills" },
  { name: "Communication", slug: "communication" },
  { name: "Social Communication", slug: "social-communication" },
  { name: "Daily Living", slug: "daily-living" },
  { name: "Behaviour Support", slug: "behaviour-support" },
  { name: "Functional Impact", slug: "functional-impact" },
  { name: "School Refusal", slug: "school-refusal" },
  { name: "Relationships", slug: "relationships" },
  { name: "Neurodiversity-Affirming", slug: "neurodiversity-affirming" },
  { name: "Demand Avoidance", slug: "demand-avoidance" },
  { name: "Developmental Delay", slug: "developmental-delay" },
  { name: "Learning Difficulties", slug: "learning-difficulties" },
  { name: "Emotional Literacy", slug: "emotional-literacy" },
  { name: "Child", slug: "child" },
  { name: "Adolescent", slug: "adolescent" },
  { name: "Adults", slug: "adults" },
  { name: "Older Adults", slug: "older-adults" },
  { name: "Parent", slug: "parent" },
  { name: "Family", slug: "family" },
  { name: "Teacher", slug: "teacher" },
  { name: "Paediatric", slug: "paediatric" },
  { name: "Early Intervention", slug: "early-intervention" },
  { name: "School-Based", slug: "school-based" },
  { name: "Workplace", slug: "workplace" },
  { name: "CBT", slug: "cbt" },
  { name: "DBT", slug: "dbt" },
  { name: "ACT", slug: "act" },
  { name: "Motivational Interviewing", slug: "motivational-interviewing" },
  { name: "Mindfulness", slug: "mindfulness" },
  { name: "Self-Compassion", slug: "self-compassion" },
  { name: "Behavioural Activation", slug: "behavioural-activation" },
  { name: "Goal Setting", slug: "goal-setting" },
  { name: "Case Formulation", slug: "case-formulation" },
  { name: "Feedback Sessions", slug: "feedback-sessions" },
  { name: "Session Planning", slug: "session-planning" },
  { name: "Therapist Tools", slug: "therapist-tools" },
  { name: "Assessment", slug: "assessment" },
  { name: "NDIS", slug: "ndis" },
  { name: "Medicare", slug: "medicare" },
  { name: "Mental Health Treatment Plan", slug: "mental-health-treatment-plan" },
  { name: "GP Referral", slug: "gp-referral" },
  { name: "Private Practice", slug: "private-practice" },
  { name: "Template", slug: "template" },
  { name: "Worksheet", slug: "worksheet" },
  { name: "Handout", slug: "handout" },
  { name: "Checklist", slug: "checklist" },
  { name: "Screener", slug: "screener" },
  { name: "Questionnaire", slug: "questionnaire" },
  { name: "Report Writing", slug: "report-writing" },
  { name: "Assessment Report", slug: "assessment-report" },
  { name: "Progress Report", slug: "progress-report" },
  { name: "Functional Capacity Assessment", slug: "functional-capacity-assessment" },
  { name: "Letter", slug: "letter" },
  { name: "Support Letters", slug: "support-letters" },
  { name: "Referral Letter", slug: "referral-letter" },
  { name: "Intake Form", slug: "intake-form" },
  { name: "Consent Form", slug: "consent-form" },
  { name: "Informed Consent", slug: "informed-consent" },
  { name: "Service Agreement", slug: "service-agreement" },
  { name: "Policy", slug: "policy" },
  { name: "Practice Policy", slug: "practice-policy" },
  { name: "Session Notes", slug: "session-notes" },
  { name: "Progress Notes", slug: "progress-notes" },
  { name: "Treatment Plan", slug: "treatment-plan" },
  { name: "Goal Plan", slug: "goal-plan" },
  { name: "Home Program", slug: "home-program" },
  { name: "Behaviour Support Plan", slug: "behaviour-support-plan" },
  { name: "Risk Assessment", slug: "risk-assessment" },
  { name: "Safety Plan", slug: "safety-plan" },
  { name: "Clinical Documentation", slug: "clinical-documentation" },
  { name: "Printable", slug: "printable" },
  { name: "Editable", slug: "editable" },
  { name: "Invoice", slug: "invoice" },
  { name: "Receipt", slug: "receipt" },
  { name: "Supervision", slug: "supervision" },
  { name: "Fine Motor", slug: "fine-motor" },
  { name: "Gross Motor", slug: "gross-motor" },
  { name: "Handwriting", slug: "handwriting" },
  { name: "AAC", slug: "aac" },
  { name: "Articulation", slug: "articulation" },
  { name: "Language", slug: "language" },
  { name: "Feeding", slug: "feeding" },
  { name: "Voice", slug: "voice" },
  { name: "Stuttering", slug: "stuttering" },
  { name: "Mobility", slug: "mobility" },
  { name: "Exercise Program", slug: "exercise-program" },
  { name: "Rehabilitation", slug: "rehabilitation" },
  { name: "Pain Management", slug: "pain-management" },
] satisfies { name: string; slug: string }[];

export const HOMEPAGE_FEATURED_CATEGORY_SLUGS = [
  "psychoeducation",
  "report-templates",
  "ndis-resources",
  "therapy-worksheets",
  "parent-handouts",
  "emotional-regulation-tools",
  "trauma-informed-practice",
  "assessment-tools",
] as const;
